# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=255, verbose_name='ID записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=14, null=True, verbose_name='ИНН')),
                ('card_id', models.IntegerField(null=True, verbose_name='Номер карточки')),
                ('middle_name', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(max_length=255, null=True, verbose_name='Дата рождения')),
                ('assigned', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('sex', models.IntegerField(null=True, verbose_name='Пол')),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_app.Department', to_field='department_id', verbose_name='Отделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.Schedules'),
        ),
    ]
