# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_id', models.IntegerField(unique=True, verbose_name='ID МИС кабинета')),
                ('name', models.CharField(max_length=255, verbose_name='Номер или название кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(unique=True, verbose_name='ID Отделения')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(unique=True, verbose_name='ID МИС доктора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/doctors', verbose_name='Изображение')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('fist_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Специальность')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.Department', to_field='department_id', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Докторы',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField(unique=True, verbose_name='Госпиталь ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название госпиталя')),
            ],
            options={
                'verbose_name': 'Госпиталь',
                'verbose_name_plural': 'Госпитали',
            },
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.IntegerField(unique=True, verbose_name='ID МИС услуги')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_id', models.IntegerField(verbose_name='ID Кабинета')),
                ('time', models.TimeField(verbose_name='Время')),
                ('busy', models.BooleanField(default=True, verbose_name='Занято')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.Date', to_field='dates', verbose_name='Дата')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.Doctor', to_field='doc_id', verbose_name='ID Досктора')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Спецификация')),
                ('cabinet', models.CharField(max_length=255, verbose_name='Кабинет')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.Doctor', to_field='doc_id', verbose_name='Доктор')),
                ('medical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.MedicalService', to_field='med_id', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_app.Hospital', to_field='hospital_id', verbose_name='Госпиталь'),
        ),
    ]
