# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0005_auto_20180125_1033'),
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='api',
            field=models.ForeignKey(blank='API сервер', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_data_app.ParserAPI'),
        ),
    ]
