# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 19:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_hospital_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='resume',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Образование и опыт'),
        ),
    ]
