# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 23:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='О нас')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст о нас')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название объявления')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news', verbose_name='Изображение новости')),
                ('anons', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Короткое описание')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_menu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сертификата')),
                ('image', models.ImageField(upload_to='images/certificates', verbose_name='Изображение сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='CompanyNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=255, verbose_name='Цифры')),
            ],
            options={
                'verbose_name': 'Цифра',
                'verbose_name_plural': 'Цифры',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон-2')),
                ('phone_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон-3')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp')),
                ('work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContactsPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data_app.Contacts', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы-Ответы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('icon', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Иконка изображения')),
            ],
            options={
                'verbose_name': 'Категория Вопроса',
                'verbose_name_plural': 'Категория Вопросов',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/features_icon', verbose_name='Иконка')),
                ('text', models.TextField(max_length=200, verbose_name='Текс')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Комментарий')),
                ('subscribe', models.BooleanField(default=True, verbose_name='Подписаться на рассылку')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='FreeConsulting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Комментарий')),
                ('subscribe', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бесплатная консультация',
                'verbose_name_plural': 'Бесплатная консультация',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news', verbose_name='Изображение новости')),
                ('anons', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Короткое описание')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название компании')),
                ('image', models.ImageField(upload_to='images/partners', verbose_name='Логотип партнеров')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на партнера')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/reviews', verbose_name='Аватарка')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео отзыв')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('location_of_review', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна получения отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название слайдера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='Изображение')),
                ('link_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео в ютубе')),
                ('video', models.FileField(blank=True, null=True, upload_to='images/videos', verbose_name='Загрузите Видео')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст на слайде')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/avatar', verbose_name='Фото сотрудника')),
                ('info', models.TextField(blank=True, max_length=150, null=True, verbose_name='Доп инфо 150 символов')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data_app.FaqCategory', verbose_name='Выберите категорию'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data_app.Category', verbose_name='Выберите категорию'),
        ),
    ]
