# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='location_of_review',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='video',
        ),
    ]
