# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
        ('base_data_app', '0002_auto_20180122_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_app.Doctor', verbose_name='Доктор'),
        ),
    ]
