# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0003_reviews_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
            ],
            options={
                'verbose_name_plural': 'Серверы',
                'verbose_name': 'Сервер',
            },
        ),
    ]
