# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0004_parserapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserapi',
            name='link',
            field=models.CharField(help_text='\n    Если нет ссылок или ни одна из ссылок не является активной, то будет использоваться сервер: http://178.216.210.23/portal/ws/wsWebPortal.1cws?wsdl\n    ', max_length=255, verbose_name='Ссылка'),
        ),
    ]
